version: 2
jobs:
  build-macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout 
      - run: echo "main"
  test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-macos
      - test






